version: 0.2
env:
  variables:
    testKey: "value1"
parameter-store:
    LOGIN_PASSWORD: /mm/codebuild/test
phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - mkdir .ebextensions
      - cd .ebextensions
      - echo "option_settings:" >> myconfig.config
      - echo "  - option_name:" "CUSTOM_ENV" >> myconfig.config
      - echo "    value:" "testing" >> myconfig.config
      - echo "  - option_name:" "CUSTOM_ENV2" >> myconfig.config
      - echo "    value:" $LOGIN_PASSWORD >> myconfig.config
artifacts:
  files:
    - '**/*'
